#!/usr/bin/env bash
# Push ONLY the whitelisted secrets from the shared env to the company-urban box.
# This keeps the box's blast radius minimal — it never holds secrets it doesn't need.
#
# To add a secret later: add it to the shared env as usual, add its KEY NAME to
# the WHITELIST below, then re-run this script. The service restarts and picks it up.
set -euo pipefail

SHARED="${SHARED_ENV_FILE:-/c/Users/User/Aiprojects/env/.env}"
BOX_IP="44.201.4.142"
KEY="${BOX_KEY:-$HOME/.ssh/cu_box.pem}"
DEST="/home/ubuntu/company-urban/.env"

# --- whitelist: only these keys are allowed on the box ---
WHITELIST=(
  ANTHROPIC_API_KEY        # ron/ronit/exec brains + claude CLI (zubin)
  RAN_TOKEN                # ran -> BoazTask
  BOAZ_GMAIL_USER          # ran -> email
  BOAZ_GMAIL_APP_PASSWORD
  BOAZ_CALENDAR_ICS_URL    # ran -> calendar
  RAN_BOT_TOKEN            # ran -> telegram
  RAN_TELEGRAM_CHAT_ID
  # deep-research Fargate worker (Phase 3) — from the stack outputs:
  RESEARCH_ECS_CLUSTER     # comms -> ecs:RunTask (which cluster)
  RESEARCH_TASK_DEF        # the Fargate task definition arn/family
  RESEARCH_SUBNET          # public subnet for the task
  RESEARCH_SG              # security group for the task
  RESEARCH_POST_TOKEN      # optional: shared secret for /rooms/{id}/post
  COMMS_PUBLIC_API         # where the worker posts the report back (default https://comms.newavera.co.il)
  AWS_REGION               # default us-east-1
  # AWS creds for ecs:RunTask: prefer an EC2 instance role on the box (no keys here).
  # If you must use static keys instead, add AWS_ACCESS_KEY_ID / AWS_SECRET_ACCESS_KEY above.
)

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT
echo "# generated by sync-box-env.sh — minimal subset, do not edit by hand" > "$TMP"
for k in "${WHITELIST[@]}"; do
  line="$(grep -E "^${k}=" "$SHARED" | head -1 || true)"
  if [ -n "$line" ]; then echo "$line" >> "$TMP"; else echo "WARN: $k not found in $SHARED" >&2; fi
done

ssh -i "$KEY" -o StrictHostKeyChecking=no "ubuntu@$BOX_IP" "mkdir -p /home/ubuntu/company-urban"
scp -i "$KEY" -o StrictHostKeyChecking=no "$TMP" "ubuntu@$BOX_IP:$DEST"
ssh -i "$KEY" "ubuntu@$BOX_IP" "chmod 600 $DEST; sudo systemctl restart comms 2>/dev/null || true"
echo "synced ${#WHITELIST[@]} whitelisted keys to the box and restarted comms (if running)"
